CREATE DATABASE IF NOT EXISTS salary_app CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE salary_app;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  salary DECIMAL(12,2) NOT NULL CHECK (salary >= 0.0),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
